; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Instcombine is not free of doing anything hazy like hoisting calls to operator
; delete. This is PR34581.

; RUN: opt -instcombine %s -S | FileCheck %s

define void @patatino(i8* %c) #0 {
; CHECK-LABEL: @patatino(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ISNULL:%.*]] = icmp eq i8* [[C:%.*]], null
; CHECK-NEXT:    br i1 [[ISNULL]], label [[DELETE_END:%.*]], label [[DELETE_NOTNULL:%.*]]
; CHECK:       delete.notnull:
; CHECK-NEXT:    call void @_ZdlPv(i8* [[C]])
; CHECK-NEXT:    br label [[DELETE_END]]
; CHECK:       delete.end:
; CHECK-NEXT:    ret void
;
entry:
  %isnull = icmp eq i8* %c, null
  br i1 %isnull, label %delete.end, label %delete.notnull

delete.notnull:
  call void @_ZdlPv(i8* %c)
  br label %delete.end

delete.end:
  ret void
}

declare void @_ZdlPv(i8*)

attributes #0 = { minsize }
