//===-- tysan_flags.inc ---------------------------------------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// TySan runtime flags.
//
//===----------------------------------------------------------------------===//
#ifndef TYSAN_FLAG
# error "Define TYSAN_FLAG prior to including this file!"
#endif

// TYSAN_FLAG(Type, Name, DefaultValue, Description)
// See COMMON_FLAG in sanitizer_flags.inc for more details.

