//===-- tbaasan_flags.inc ---------------------------------------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// TBAASan runtime flags.
//
//===----------------------------------------------------------------------===//
#ifndef TBAASAN_FLAG
# error "Define TBAASAN_FLAG prior to including this file!"
#endif

// TBAASAN_FLAG(Type, Name, DefaultValue, Description)
// See COMMON_FLAG in sanitizer_flags.inc for more details.

