; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mcpu=pwr8 -ppc-enable-memcpy-loops=true -ppc-memcpy-unknown-loops=true < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-n32:64"
target triple = "powerpc64le-unknown-linux-gnu"

@X = local_unnamed_addr global i32 0, align 4

; Function Attrs: inlinehint noinline nounwind
define signext i32 @_Z3fooPiS_i(i32* nocapture %buffer1, i32* nocapture readonly %buffer2, i32 signext %SIZE) local_unnamed_addr #2 !prof !29 {
; CHECK-LABEL: _Z3fooPiS_i:
; CHECK:       # BB#0: # %entry
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    std 0, 16(1)
; CHECK-NEXT:    stdu 1, -64(1)
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    .cfi_offset r29, -24
; CHECK-NEXT:    .cfi_offset r30, -16
; CHECK-NEXT:    std 29, 40(1) # 8-byte Folded Spill
; CHECK-NEXT:    addis 29, 2, .LC0@toc@ha
; CHECK-NEXT:    std 30, 48(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 30, 5
; CHECK-NEXT:    ld 5, .LC0@toc@l(29)
; CHECK-NEXT:    mr 29, 3
; CHECK-NEXT:    lwz 5, 0(5)
; CHECK-NEXT:    cmpw 5, 30
; CHECK-NEXT:    ble 0, .LBB0_9
; CHECK-NEXT:  # BB#1: # %if.then
; CHECK-NEXT:    cmpldi 30, 128
; CHECK-NEXT:    bgt 0, .LBB0_8
; CHECK-NEXT:  # BB#2:
; CHECK-NEXT:    rldicl. 5, 30, 58, 6
; CHECK-NEXT:    clrldi 3, 30, 58
; CHECK-NEXT:    beq 0, .LBB0_5
; CHECK-NEXT:  # BB#3: # %loop-memcpy-expansion.preheader
; CHECK-NEXT:    mtctr 5
; CHECK-NEXT:    li 5, 16
; CHECK-NEXT:    li 6, 32
; CHECK-NEXT:    li 7, 48
; CHECK-NEXT:    mr 8, 4
; CHECK-NEXT:    mr 9, 29
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_4: # %loop-memcpy-expansion
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lxvd2x 0, 8, 6
; CHECK-NEXT:    lxvd2x 1, 8, 7
; CHECK-NEXT:    lxvd2x 2, 8, 5
; CHECK-NEXT:    lxvd2x 3, 0, 8
; CHECK-NEXT:    addi 8, 8, 64
; CHECK-NEXT:    stxvd2x 1, 9, 7
; CHECK-NEXT:    stxvd2x 0, 9, 6
; CHECK-NEXT:    stxvd2x 2, 9, 5
; CHECK-NEXT:    stxvd2x 3, 0, 9
; CHECK-NEXT:    addi 9, 9, 64
; CHECK-NEXT:    bdnz .LBB0_4
; CHECK-NEXT:  .LBB0_5: # %loop-memcpy-residual-header
; CHECK-NEXT:    cmpldi 3, 0
; CHECK-NEXT:    beq 0, .LBB0_9
; CHECK-NEXT:  # BB#6: # %loop-memcpy-residual.preheader
; CHECK-NEXT:    addi 5, 30, -1
; CHECK-NEXT:    mtctr 3
; CHECK-NEXT:    sub 5, 5, 3
; CHECK-NEXT:    add 4, 4, 5
; CHECK-NEXT:    add 5, 29, 5
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_7: # %loop-memcpy-residual
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lbzu 3, 1(4)
; CHECK-NEXT:    stbu 3, 1(5)
; CHECK-NEXT:    bdnz .LBB0_7
; CHECK-NEXT:    b .LBB0_9
; CHECK-NEXT:  .LBB0_8:
; CHECK-NEXT:    mr 3, 29
; CHECK-NEXT:    mr 5, 30
; CHECK-NEXT:    bl memcpy
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_9: # %if.end
; CHECK-NEXT:    sldi 3, 30, 2
; CHECK-NEXT:    ld 30, 48(1) # 8-byte Folded Reload
; CHECK-NEXT:    lwax 3, 29, 3
; CHECK-NEXT:    ld 29, 40(1) # 8-byte Folded Reload
; CHECK-NEXT:    addi 1, 1, 64
; CHECK-NEXT:    ld 0, 16(1)
; CHECK-NEXT:    mtlr 0
; CHECK-NEXT:    blr
entry:
  %0 = load i32, i32* @X, align 4, !tbaa !30
  %cmp = icmp sgt i32 %0, %SIZE
  %conv = sext i32 %SIZE to i64
  br i1 %cmp, label %if.then, label %if.end, !prof !34

if.then:                                          ; preds = %entry
  %1 = bitcast i32* %buffer1 to i8*
  %2 = bitcast i32* %buffer2 to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i64(i8* %1, i8* %2, i64 %conv, i32 4, i1 false)
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  %arrayidx = getelementptr inbounds i32, i32* %buffer1, i64 %conv
  %3 = load i32, i32* %arrayidx, align 4, !tbaa !30
  ret i32 %3
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture writeonly, i8* nocapture readonly, i64, i32, i1) #3

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!28}

!0 = !{i32 1, !"PIC Level", i32 2}
!1 = !{i32 1, !"ProfileSummary", !2}
!2 = !{!3, !4, !5, !6, !7, !8, !9, !10}
!3 = !{!"ProfileFormat", !"InstrProf"}
!4 = !{!"TotalCount", i64 396}
!5 = !{!"MaxCount", i64 200}
!6 = !{!"MaxInternalCount", i64 20}
!7 = !{!"MaxFunctionCount", i64 200}
!8 = !{!"NumCounts", i64 16}
!9 = !{!"NumFunctions", i64 5}
!10 = !{!"DetailedSummary", !11}
!11 = !{!12, !13, !14, !15, !16, !17, !17, !18, !18, !19, !20, !21, !22, !23, !24, !25, !26, !27}
!12 = !{i32 10000, i64 200, i32 1}
!13 = !{i32 100000, i64 200, i32 1}
!14 = !{i32 200000, i64 200, i32 1}
!15 = !{i32 300000, i64 200, i32 1}
!16 = !{i32 400000, i64 200, i32 1}
!17 = !{i32 500000, i64 200, i32 1}
!18 = !{i32 600000, i64 100, i32 2}
!19 = !{i32 700000, i64 100, i32 2}
!20 = !{i32 800000, i64 30, i32 3}
!21 = !{i32 900000, i64 18, i32 5}
!22 = !{i32 950000, i64 10, i32 7}
!23 = !{i32 990000, i64 2, i32 10}
!24 = !{i32 999000, i64 2, i32 10}
!25 = !{i32 999900, i64 2, i32 10}
!26 = !{i32 999990, i64 2, i32 10}
!27 = !{i32 999999, i64 2, i32 10}
!28 = !{!"clang version 5.0.0 (git@github.ibm.com:llvm/clang.git d10c298f0fbab013ff45d395a3de8aa14085ccae) (llvm/llvm.git c3fbf2fa5a1161b7ddb3a64220e99a7ff2cb4bc6)"}
!29 = !{!"function_entry_count", i64 30}
!30 = !{!31, !31, i64 0}
!31 = !{!"int", !32, i64 0}
!32 = !{!"omnipotent char", !33, i64 0}
!33 = !{!"Simple C++ TBAA"}
!34 = !{!"branch_weights", i32 30, i32 10}
!35 = !{!"function_entry_count", i64 2}
!36 = !{!"branch_weights", i32 2, i32 200}
!37 = !{!38, !38, i64 0}
!38 = !{!"vtable pointer", !33, i64 0}
!39 = !{!40, !41, i64 240}
!40 = !{!"_ZTSSt9basic_iosIcSt11char_traitsIcEE", !41, i64 216, !32, i64 224, !42, i64 225, !41, i64 232, !41, i64 240, !41, i64 248, !41, i64 256}
!41 = !{!"any pointer", !32, i64 0}
!42 = !{!"bool", !32, i64 0}
!43 = !{!"branch_weights", i32 0, i32 20}
!44 = !{!45, !32, i64 56}
!45 = !{!"_ZTSSt5ctypeIcE", !41, i64 16, !42, i64 24, !41, i64 32, !41, i64 40, !41, i64 48, !32, i64 56, !32, i64 57, !32, i64 313, !32, i64 569}
!46 = !{!"branch_weights", i32 2, i32 18}
!47 = !{!32, !32, i64 0}
!48 = !{!"VP", i32 0, i64 1, i64 0, i64 1}
!49 = !{!"branch_weights", i32 20, i32 2}
!50 = !{!"function_entry_count", i64 3}
!51 = !{!"memcpy2.cpp:_GLOBAL__sub_I_memcpy2.cpp"}