; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=powerpc64le-unknown-unknown -mcpu=pwr8 \
; RUN:   -ppc-late-peephole -verify-machineinstrs | FileCheck %s
%struct.x0 = type { i8 }

@.str = private unnamed_addr constant [1 x i8] zeroinitializer, align 1

define void @_Z2x6v() {
; CHECK-LABEL: _Z2x6v:
; CHECK:       # BB#0: # %entry
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    std 0, 16(1)
; CHECK-NEXT:    stdu 1, -64(1)
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    .cfi_offset r30, -16
; CHECK-NEXT:    addi 3, 1, 40
; CHECK-NEXT:    std 30, 48(1) # 8-byte Folded Spill
; CHECK-NEXT:    bl _ZN2x02x1Ev
; CHECK-NEXT:    nop
; CHECK-NEXT:    mr 30, 3
; CHECK-NEXT:    addis 12, 2, .L.str@toc@ha
; CHECK-NEXT:    addi 4, 12, .L.str@toc@l
; Note: previously there was an mr 3, 30 here.
; CHECK-NEXT:    bl _ZN2x02x4EPKc
; CHECK-NEXT:    nop
; CHECK-NEXT:    li 4, 0
; CHECK-NEXT:    mr 3, 30
; CHECK-NEXT:    bl _ZN2x0lsIiEEvT_
; CHECK-NEXT:    nop
; CHECK-NEXT:    ld 30, 48(1) # 8-byte Folded Reload
; CHECK-NEXT:    addi 1, 1, 64
; CHECK-NEXT:    ld 0, 16(1)
; CHECK-NEXT:    mtlr 0
; CHECK-NEXT:    blr
entry:
  %ref.tmp = alloca %struct.x0, align 1
  %0 = getelementptr inbounds %struct.x0, %struct.x0* %ref.tmp, i64 0, i32 0
  call void @llvm.lifetime.start.p0i8(i64 1, i8* nonnull %0)
  %call = call dereferenceable(1) %struct.x0* @_ZN2x02x1Ev(%struct.x0* nonnull %ref.tmp)
  call void @_ZN2x02x4EPKc(%struct.x0* nonnull %call, i8* nonnull getelementptr inbounds ([1 x i8], [1 x i8]* @.str, i64 0, i64 0))
  call void @_ZN2x0lsIiEEvT_(%struct.x0* nonnull %call, i32 signext 0)
  call void @llvm.lifetime.end.p0i8(i64 1, i8* nonnull %0)
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture)

declare dereferenceable(1) %struct.x0* @_ZN2x02x1Ev(%struct.x0*)

declare void @_ZN2x0lsIiEEvT_(%struct.x0*, i32 signext)

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture)

declare void @_ZN2x02x4EPKc(%struct.x0*, i8*)
