; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2     | FileCheck %s --check-prefix=CHECK --check-prefix=SSE --check-prefix=SSE-RECIP
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx      | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=AVX-RECIP
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx,+fma | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=FMA-RECIP
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=btver2     | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=BTVER2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=sandybridge| FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=SANDY
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=haswell    | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=HASWELL
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=haswell -mattr=-fma | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=HASWELL-NO-FMA
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=knl        | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=AVX512 --check-prefix=KNL
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=skx        | FileCheck %s --check-prefix=CHECK --check-prefix=AVX --check-prefix=AVX512 --check-prefix=SKX

; If the target's divss/divps instructions are substantially
; slower than rcpss/rcpps with a Newton-Raphson refinement,
; we should generate the estimate sequence.

; See PR21385 ( http://llvm.org/bugs/show_bug.cgi?id=21385 )
; for details about the accuracy, speed, and implementation
; differences of x86 reciprocal estimates.

define float @f32_no_estimate(float %x) #0 {
; SSE-LABEL: f32_no_estimate:
; SSE:       # BB#0:
; SSE-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SSE-NEXT:    divss %xmm0, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-LABEL: f32_no_estimate:
; AVX:       # BB#0:
; AVX-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; AVX-NEXT:    vdivss %xmm0, %xmm1, %xmm0
; AVX-NEXT:    retq
  %div = fdiv fast float 1.0, %x
  ret float %div
}

define float @f32_one_step(float %x) #1 {
; SSE-LABEL: f32_one_step:
; SSE:       # BB#0:
; SSE-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SSE-NEXT:    rcpss %xmm0, %xmm2
; SSE-NEXT:    mulss %xmm2, %xmm0
; SSE-NEXT:    subss %xmm0, %xmm1
; SSE-NEXT:    mulss %xmm2, %xmm1
; SSE-NEXT:    addss %xmm2, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: f32_one_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; AVX-RECIP-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vsubss %xmm0, %xmm1, %xmm0
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vaddss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: f32_one_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vrcpss %xmm0, %xmm0, %xmm1
; FMA-RECIP-NEXT:    vfnmadd213ss {{.*}}(%rip), %xmm1, %xmm0
; FMA-RECIP-NEXT:    vfmadd132ss %xmm1, %xmm1, %xmm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: f32_one_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; BTVER2-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; BTVER2-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vsubss %xmm0, %xmm1, %xmm0
; BTVER2-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vaddss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: f32_one_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SANDY-NEXT:    vdivss %xmm0, %xmm1, %xmm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: f32_one_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vrcpss %xmm0, %xmm0, %xmm1
; HASWELL-NEXT:    vfnmadd213ss {{.*}}(%rip), %xmm1, %xmm0
; HASWELL-NEXT:    vfmadd132ss %xmm1, %xmm1, %xmm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: f32_one_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; HASWELL-NO-FMA-NEXT:    vdivss %xmm0, %xmm1, %xmm0
; HASWELL-NO-FMA-NEXT:    retq
;
; AVX512-LABEL: f32_one_step:
; AVX512:       # BB#0:
; AVX512-NEXT:    vrcp14ss %xmm0, %xmm0, %xmm1
; AVX512-NEXT:    vfnmadd213ss {{.*}}(%rip), %xmm1, %xmm0
; AVX512-NEXT:    vfmadd132ss %xmm1, %xmm1, %xmm0
; AVX512-NEXT:    retq
  %div = fdiv fast float 1.0, %x
  ret float %div
}

define float @f32_two_step(float %x) #2 {
; SSE-LABEL: f32_two_step:
; SSE:       # BB#0:
; SSE-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SSE-NEXT:    rcpss %xmm0, %xmm2
; SSE-NEXT:    movaps %xmm0, %xmm3
; SSE-NEXT:    mulss %xmm2, %xmm3
; SSE-NEXT:    movaps %xmm1, %xmm4
; SSE-NEXT:    subss %xmm3, %xmm4
; SSE-NEXT:    mulss %xmm2, %xmm4
; SSE-NEXT:    addss %xmm2, %xmm4
; SSE-NEXT:    mulss %xmm4, %xmm0
; SSE-NEXT:    subss %xmm0, %xmm1
; SSE-NEXT:    mulss %xmm4, %xmm1
; SSE-NEXT:    addss %xmm4, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: f32_two_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; AVX-RECIP-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm0, %xmm3
; AVX-RECIP-NEXT:    vsubss %xmm3, %xmm1, %xmm3
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm3, %xmm3
; AVX-RECIP-NEXT:    vaddss %xmm2, %xmm3, %xmm2
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vsubss %xmm0, %xmm1, %xmm0
; AVX-RECIP-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vaddss %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: f32_two_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; FMA-RECIP-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; FMA-RECIP-NEXT:    vmovaps %xmm0, %xmm3
; FMA-RECIP-NEXT:    vfnmadd132ss %xmm2, %xmm1, %xmm3
; FMA-RECIP-NEXT:    vfmadd132ss %xmm2, %xmm2, %xmm3
; FMA-RECIP-NEXT:    vfnmadd132ss %xmm3, %xmm1, %xmm0
; FMA-RECIP-NEXT:    vfmadd132ss %xmm3, %xmm3, %xmm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: f32_two_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; BTVER2-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; BTVER2-NEXT:    vmulss %xmm2, %xmm0, %xmm3
; BTVER2-NEXT:    vsubss %xmm3, %xmm1, %xmm3
; BTVER2-NEXT:    vmulss %xmm2, %xmm3, %xmm3
; BTVER2-NEXT:    vaddss %xmm2, %xmm3, %xmm2
; BTVER2-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vsubss %xmm0, %xmm1, %xmm0
; BTVER2-NEXT:    vmulss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vaddss %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: f32_two_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SANDY-NEXT:    vdivss %xmm0, %xmm1, %xmm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: f32_two_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; HASWELL-NEXT:    vrcpss %xmm0, %xmm0, %xmm2
; HASWELL-NEXT:    vmovaps %xmm0, %xmm3
; HASWELL-NEXT:    vfnmadd132ss %xmm2, %xmm1, %xmm3
; HASWELL-NEXT:    vfmadd132ss %xmm2, %xmm2, %xmm3
; HASWELL-NEXT:    vfnmadd132ss %xmm3, %xmm1, %xmm0
; HASWELL-NEXT:    vfmadd132ss %xmm3, %xmm3, %xmm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: f32_two_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; HASWELL-NO-FMA-NEXT:    vdivss %xmm0, %xmm1, %xmm0
; HASWELL-NO-FMA-NEXT:    retq
;
; AVX512-LABEL: f32_two_step:
; AVX512:       # BB#0:
; AVX512-NEXT:    vrcp14ss %xmm0, %xmm0, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; AVX512-NEXT:    vmovaps %xmm1, %xmm3
; AVX512-NEXT:    vfnmadd213ss %xmm2, %xmm0, %xmm3
; AVX512-NEXT:    vfmadd132ss %xmm1, %xmm1, %xmm3
; AVX512-NEXT:    vfnmadd213ss %xmm2, %xmm3, %xmm0
; AVX512-NEXT:    vfmadd132ss %xmm3, %xmm3, %xmm0
; AVX512-NEXT:    retq
  %div = fdiv fast float 1.0, %x
  ret float %div
}

define <4 x float> @v4f32_no_estimate(<4 x float> %x) #0 {
; SSE-LABEL: v4f32_no_estimate:
; SSE:       # BB#0:
; SSE-NEXT:    movaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    divps %xmm0, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v4f32_no_estimate:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v4f32_no_estimate:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; FMA-RECIP-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v4f32_no_estimate:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v4f32_no_estimate:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v4f32_no_estimate:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v4f32_no_estimate:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NO-FMA-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; HASWELL-NO-FMA-NEXT:    retq
;
; AVX512-LABEL: v4f32_no_estimate:
; AVX512:       # BB#0:
; AVX512-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; AVX512-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; AVX512-NEXT:    retq
  %div = fdiv fast <4 x float> <float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <4 x float> %div
}

define <4 x float> @v4f32_one_step(<4 x float> %x) #1 {
; SSE-LABEL: v4f32_one_step:
; SSE:       # BB#0:
; SSE-NEXT:    movaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    rcpps %xmm0, %xmm2
; SSE-NEXT:    mulps %xmm2, %xmm0
; SSE-NEXT:    subps %xmm0, %xmm1
; SSE-NEXT:    mulps %xmm2, %xmm1
; SSE-NEXT:    addps %xmm2, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v4f32_one_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vrcpps %xmm0, %xmm2
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vsubps %xmm0, %xmm1, %xmm0
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vaddps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v4f32_one_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vrcpps %xmm0, %xmm1
; FMA-RECIP-NEXT:    vfnmadd213ps {{.*}}(%rip), %xmm1, %xmm0
; FMA-RECIP-NEXT:    vfmadd132ps %xmm1, %xmm1, %xmm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v4f32_one_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vrcpps %xmm0, %xmm2
; BTVER2-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vsubps %xmm0, %xmm1, %xmm0
; BTVER2-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vaddps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v4f32_one_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v4f32_one_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NEXT:    vrcpps %xmm0, %xmm2
; HASWELL-NEXT:    vfnmadd231ps %xmm2, %xmm0, %xmm1
; HASWELL-NEXT:    vfmadd132ps %xmm2, %xmm2, %xmm1
; HASWELL-NEXT:    vmovaps %xmm1, %xmm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v4f32_one_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NO-FMA-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; HASWELL-NO-FMA-NEXT:    retq
;
; KNL-LABEL: v4f32_one_step:
; KNL:       # BB#0:
; KNL-NEXT:    vrcpps %xmm0, %xmm1
; KNL-NEXT:    vbroadcastss {{.*}}(%rip), %xmm2
; KNL-NEXT:    vfnmadd213ps %xmm2, %xmm1, %xmm0
; KNL-NEXT:    vfmadd132ps %xmm1, %xmm1, %xmm0
; KNL-NEXT:    retq
;
; SKX-LABEL: v4f32_one_step:
; SKX:       # BB#0:
; SKX-NEXT:    vrcp14ps %xmm0, %xmm1
; SKX-NEXT:    vfnmadd213ps {{.*}}(%rip){1to4}, %xmm1, %xmm0
; SKX-NEXT:    vfmadd132ps %xmm1, %xmm1, %xmm0
; SKX-NEXT:    retq
  %div = fdiv fast <4 x float> <float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <4 x float> %div
}

define <4 x float> @v4f32_two_step(<4 x float> %x) #2 {
; SSE-LABEL: v4f32_two_step:
; SSE:       # BB#0:
; SSE-NEXT:    movaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    rcpps %xmm0, %xmm2
; SSE-NEXT:    movaps %xmm0, %xmm3
; SSE-NEXT:    mulps %xmm2, %xmm3
; SSE-NEXT:    movaps %xmm1, %xmm4
; SSE-NEXT:    subps %xmm3, %xmm4
; SSE-NEXT:    mulps %xmm2, %xmm4
; SSE-NEXT:    addps %xmm2, %xmm4
; SSE-NEXT:    mulps %xmm4, %xmm0
; SSE-NEXT:    subps %xmm0, %xmm1
; SSE-NEXT:    mulps %xmm4, %xmm1
; SSE-NEXT:    addps %xmm4, %xmm1
; SSE-NEXT:    movaps %xmm1, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v4f32_two_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vrcpps %xmm0, %xmm2
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm0, %xmm3
; AVX-RECIP-NEXT:    vsubps %xmm3, %xmm1, %xmm3
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm3, %xmm3
; AVX-RECIP-NEXT:    vaddps %xmm2, %xmm3, %xmm2
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vsubps %xmm0, %xmm1, %xmm0
; AVX-RECIP-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    vaddps %xmm2, %xmm0, %xmm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v4f32_two_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; FMA-RECIP-NEXT:    vrcpps %xmm0, %xmm2
; FMA-RECIP-NEXT:    vmovaps %xmm0, %xmm3
; FMA-RECIP-NEXT:    vfnmadd132ps %xmm2, %xmm1, %xmm3
; FMA-RECIP-NEXT:    vfmadd132ps %xmm2, %xmm2, %xmm3
; FMA-RECIP-NEXT:    vfnmadd132ps %xmm3, %xmm1, %xmm0
; FMA-RECIP-NEXT:    vfmadd132ps %xmm3, %xmm3, %xmm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v4f32_two_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vrcpps %xmm0, %xmm2
; BTVER2-NEXT:    vmulps %xmm2, %xmm0, %xmm3
; BTVER2-NEXT:    vsubps %xmm3, %xmm1, %xmm3
; BTVER2-NEXT:    vmulps %xmm2, %xmm3, %xmm3
; BTVER2-NEXT:    vaddps %xmm2, %xmm3, %xmm2
; BTVER2-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vsubps %xmm0, %xmm1, %xmm0
; BTVER2-NEXT:    vmulps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    vaddps %xmm2, %xmm0, %xmm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v4f32_two_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v4f32_two_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NEXT:    vrcpps %xmm0, %xmm2
; HASWELL-NEXT:    vmovaps %xmm0, %xmm3
; HASWELL-NEXT:    vfnmadd132ps %xmm2, %xmm1, %xmm3
; HASWELL-NEXT:    vfmadd132ps %xmm2, %xmm2, %xmm3
; HASWELL-NEXT:    vfnmadd132ps %xmm3, %xmm1, %xmm0
; HASWELL-NEXT:    vfmadd132ps %xmm3, %xmm3, %xmm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v4f32_two_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %xmm1
; HASWELL-NO-FMA-NEXT:    vdivps %xmm0, %xmm1, %xmm0
; HASWELL-NO-FMA-NEXT:    retq
;
; KNL-LABEL: v4f32_two_step:
; KNL:       # BB#0:
; KNL-NEXT:    vrcpps %xmm0, %xmm1
; KNL-NEXT:    vbroadcastss {{.*}}(%rip), %xmm2
; KNL-NEXT:    vmovaps %xmm1, %xmm3
; KNL-NEXT:    vfnmadd213ps %xmm2, %xmm0, %xmm3
; KNL-NEXT:    vfmadd132ps %xmm1, %xmm1, %xmm3
; KNL-NEXT:    vfnmadd213ps %xmm2, %xmm3, %xmm0
; KNL-NEXT:    vfmadd132ps %xmm3, %xmm3, %xmm0
; KNL-NEXT:    retq
;
; SKX-LABEL: v4f32_two_step:
; SKX:       # BB#0:
; SKX-NEXT:    vrcp14ps %xmm0, %xmm1
; SKX-NEXT:    vbroadcastss {{.*}}(%rip), %xmm2
; SKX-NEXT:    vmovaps %xmm1, %xmm3
; SKX-NEXT:    vfnmadd213ps %xmm2, %xmm0, %xmm3
; SKX-NEXT:    vfmadd132ps %xmm1, %xmm1, %xmm3
; SKX-NEXT:    vfnmadd213ps %xmm2, %xmm3, %xmm0
; SKX-NEXT:    vfmadd132ps %xmm3, %xmm3, %xmm0
; SKX-NEXT:    retq
  %div = fdiv fast <4 x float> <float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <4 x float> %div
}

define <8 x float> @v8f32_no_estimate(<8 x float> %x) #0 {
; SSE-LABEL: v8f32_no_estimate:
; SSE:       # BB#0:
; SSE-NEXT:    movaps {{.*#+}} xmm2 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    movaps %xmm2, %xmm3
; SSE-NEXT:    divps %xmm0, %xmm3
; SSE-NEXT:    divps %xmm1, %xmm2
; SSE-NEXT:    movaps %xmm3, %xmm0
; SSE-NEXT:    movaps %xmm2, %xmm1
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v8f32_no_estimate:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v8f32_no_estimate:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; FMA-RECIP-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v8f32_no_estimate:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v8f32_no_estimate:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v8f32_no_estimate:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v8f32_no_estimate:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NO-FMA-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; HASWELL-NO-FMA-NEXT:    retq
;
; AVX512-LABEL: v8f32_no_estimate:
; AVX512:       # BB#0:
; AVX512-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; AVX512-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; AVX512-NEXT:    retq
  %div = fdiv fast <8 x float> <float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <8 x float> %div
}

define <8 x float> @v8f32_one_step(<8 x float> %x) #1 {
; SSE-LABEL: v8f32_one_step:
; SSE:       # BB#0:
; SSE-NEXT:    movaps {{.*#+}} xmm2 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    rcpps %xmm0, %xmm4
; SSE-NEXT:    mulps %xmm4, %xmm0
; SSE-NEXT:    movaps %xmm2, %xmm3
; SSE-NEXT:    subps %xmm0, %xmm3
; SSE-NEXT:    mulps %xmm4, %xmm3
; SSE-NEXT:    addps %xmm4, %xmm3
; SSE-NEXT:    rcpps %xmm1, %xmm0
; SSE-NEXT:    mulps %xmm0, %xmm1
; SSE-NEXT:    subps %xmm1, %xmm2
; SSE-NEXT:    mulps %xmm0, %xmm2
; SSE-NEXT:    addps %xmm0, %xmm2
; SSE-NEXT:    movaps %xmm3, %xmm0
; SSE-NEXT:    movaps %xmm2, %xmm1
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v8f32_one_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vrcpps %ymm0, %ymm2
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    vsubps %ymm0, %ymm1, %ymm0
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    vaddps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v8f32_one_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vrcpps %ymm0, %ymm1
; FMA-RECIP-NEXT:    vfnmadd213ps {{.*}}(%rip), %ymm1, %ymm0
; FMA-RECIP-NEXT:    vfmadd132ps %ymm1, %ymm1, %ymm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v8f32_one_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vrcpps %ymm0, %ymm2
; BTVER2-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    vsubps %ymm0, %ymm1, %ymm0
; BTVER2-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    vaddps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v8f32_one_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v8f32_one_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vrcpps %ymm0, %ymm2
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NEXT:    vfnmadd231ps %ymm2, %ymm0, %ymm1
; HASWELL-NEXT:    vfmadd132ps %ymm2, %ymm2, %ymm1
; HASWELL-NEXT:    vmovaps %ymm1, %ymm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v8f32_one_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NO-FMA-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; HASWELL-NO-FMA-NEXT:    retq
;
; KNL-LABEL: v8f32_one_step:
; KNL:       # BB#0:
; KNL-NEXT:    vrcpps %ymm0, %ymm1
; KNL-NEXT:    vbroadcastss {{.*}}(%rip), %ymm2
; KNL-NEXT:    vfnmadd213ps %ymm2, %ymm1, %ymm0
; KNL-NEXT:    vfmadd132ps %ymm1, %ymm1, %ymm0
; KNL-NEXT:    retq
;
; SKX-LABEL: v8f32_one_step:
; SKX:       # BB#0:
; SKX-NEXT:    vrcp14ps %ymm0, %ymm1
; SKX-NEXT:    vfnmadd213ps {{.*}}(%rip){1to8}, %ymm1, %ymm0
; SKX-NEXT:    vfmadd132ps %ymm1, %ymm1, %ymm0
; SKX-NEXT:    retq
  %div = fdiv fast <8 x float> <float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <8 x float> %div
}

define <8 x float> @v8f32_two_step(<8 x float> %x) #2 {
; SSE-LABEL: v8f32_two_step:
; SSE:       # BB#0:
; SSE-NEXT:    movaps %xmm1, %xmm2
; SSE-NEXT:    movaps {{.*#+}} xmm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SSE-NEXT:    rcpps %xmm0, %xmm3
; SSE-NEXT:    movaps %xmm0, %xmm4
; SSE-NEXT:    mulps %xmm3, %xmm4
; SSE-NEXT:    movaps %xmm1, %xmm5
; SSE-NEXT:    subps %xmm4, %xmm5
; SSE-NEXT:    mulps %xmm3, %xmm5
; SSE-NEXT:    addps %xmm3, %xmm5
; SSE-NEXT:    mulps %xmm5, %xmm0
; SSE-NEXT:    movaps %xmm1, %xmm3
; SSE-NEXT:    subps %xmm0, %xmm3
; SSE-NEXT:    mulps %xmm5, %xmm3
; SSE-NEXT:    addps %xmm5, %xmm3
; SSE-NEXT:    rcpps %xmm2, %xmm0
; SSE-NEXT:    movaps %xmm2, %xmm4
; SSE-NEXT:    mulps %xmm0, %xmm4
; SSE-NEXT:    movaps %xmm1, %xmm5
; SSE-NEXT:    subps %xmm4, %xmm5
; SSE-NEXT:    mulps %xmm0, %xmm5
; SSE-NEXT:    addps %xmm0, %xmm5
; SSE-NEXT:    mulps %xmm5, %xmm2
; SSE-NEXT:    subps %xmm2, %xmm1
; SSE-NEXT:    mulps %xmm5, %xmm1
; SSE-NEXT:    addps %xmm5, %xmm1
; SSE-NEXT:    movaps %xmm3, %xmm0
; SSE-NEXT:    retq
;
; AVX-RECIP-LABEL: v8f32_two_step:
; AVX-RECIP:       # BB#0:
; AVX-RECIP-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; AVX-RECIP-NEXT:    vrcpps %ymm0, %ymm2
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm0, %ymm3
; AVX-RECIP-NEXT:    vsubps %ymm3, %ymm1, %ymm3
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm3, %ymm3
; AVX-RECIP-NEXT:    vaddps %ymm2, %ymm3, %ymm2
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    vsubps %ymm0, %ymm1, %ymm0
; AVX-RECIP-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    vaddps %ymm2, %ymm0, %ymm0
; AVX-RECIP-NEXT:    retq
;
; FMA-RECIP-LABEL: v8f32_two_step:
; FMA-RECIP:       # BB#0:
; FMA-RECIP-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; FMA-RECIP-NEXT:    vrcpps %ymm0, %ymm2
; FMA-RECIP-NEXT:    vmovaps %ymm0, %ymm3
; FMA-RECIP-NEXT:    vfnmadd132ps %ymm2, %ymm1, %ymm3
; FMA-RECIP-NEXT:    vfmadd132ps %ymm2, %ymm2, %ymm3
; FMA-RECIP-NEXT:    vfnmadd132ps %ymm3, %ymm1, %ymm0
; FMA-RECIP-NEXT:    vfmadd132ps %ymm3, %ymm3, %ymm0
; FMA-RECIP-NEXT:    retq
;
; BTVER2-LABEL: v8f32_two_step:
; BTVER2:       # BB#0:
; BTVER2-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; BTVER2-NEXT:    vrcpps %ymm0, %ymm2
; BTVER2-NEXT:    vmulps %ymm2, %ymm0, %ymm3
; BTVER2-NEXT:    vsubps %ymm3, %ymm1, %ymm3
; BTVER2-NEXT:    vmulps %ymm2, %ymm3, %ymm3
; BTVER2-NEXT:    vaddps %ymm2, %ymm3, %ymm2
; BTVER2-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    vsubps %ymm0, %ymm1, %ymm0
; BTVER2-NEXT:    vmulps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    vaddps %ymm2, %ymm0, %ymm0
; BTVER2-NEXT:    retq
;
; SANDY-LABEL: v8f32_two_step:
; SANDY:       # BB#0:
; SANDY-NEXT:    vmovaps {{.*#+}} ymm1 = [1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00]
; SANDY-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; SANDY-NEXT:    retq
;
; HASWELL-LABEL: v8f32_two_step:
; HASWELL:       # BB#0:
; HASWELL-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NEXT:    vrcpps %ymm0, %ymm2
; HASWELL-NEXT:    vmovaps %ymm0, %ymm3
; HASWELL-NEXT:    vfnmadd132ps %ymm2, %ymm1, %ymm3
; HASWELL-NEXT:    vfmadd132ps %ymm2, %ymm2, %ymm3
; HASWELL-NEXT:    vfnmadd132ps %ymm3, %ymm1, %ymm0
; HASWELL-NEXT:    vfmadd132ps %ymm3, %ymm3, %ymm0
; HASWELL-NEXT:    retq
;
; HASWELL-NO-FMA-LABEL: v8f32_two_step:
; HASWELL-NO-FMA:       # BB#0:
; HASWELL-NO-FMA-NEXT:    vbroadcastss {{.*}}(%rip), %ymm1
; HASWELL-NO-FMA-NEXT:    vdivps %ymm0, %ymm1, %ymm0
; HASWELL-NO-FMA-NEXT:    retq
;
; KNL-LABEL: v8f32_two_step:
; KNL:       # BB#0:
; KNL-NEXT:    vrcpps %ymm0, %ymm1
; KNL-NEXT:    vbroadcastss {{.*}}(%rip), %ymm2
; KNL-NEXT:    vmovaps %ymm1, %ymm3
; KNL-NEXT:    vfnmadd213ps %ymm2, %ymm0, %ymm3
; KNL-NEXT:    vfmadd132ps %ymm1, %ymm1, %ymm3
; KNL-NEXT:    vfnmadd213ps %ymm2, %ymm3, %ymm0
; KNL-NEXT:    vfmadd132ps %ymm3, %ymm3, %ymm0
; KNL-NEXT:    retq
;
; SKX-LABEL: v8f32_two_step:
; SKX:       # BB#0:
; SKX-NEXT:    vrcp14ps %ymm0, %ymm1
; SKX-NEXT:    vbroadcastss {{.*}}(%rip), %ymm2
; SKX-NEXT:    vmovaps %ymm1, %ymm3
; SKX-NEXT:    vfnmadd213ps %ymm2, %ymm0, %ymm3
; SKX-NEXT:    vfmadd132ps %ymm1, %ymm1, %ymm3
; SKX-NEXT:    vfnmadd213ps %ymm2, %ymm3, %ymm0
; SKX-NEXT:    vfmadd132ps %ymm3, %ymm3, %ymm0
; SKX-NEXT:    retq
  %div = fdiv fast <8 x float> <float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0>, %x
  ret <8 x float> %div
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="!divf,!vec-divf" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="divf,vec-divf" }
attributes #2 = { "unsafe-fp-math"="true" "reciprocal-estimates"="divf:2,vec-divf:2" }

