; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i386-unknown-linux-gnu -mcpu=slm -relocation-model=pic | FileCheck %s --check-prefix=CHECK

define fastcc void @foo() unnamed_addr #0 {
; CHECK-LABEL: foo:
; CHECK:       # BB#0: # %entry
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    xorps %xmm2, %xmm2
; CHECK-NEXT:    movss {{.*#+}} xmm3 = mem[0],zero,zero,zero
; CHECK-NEXT:    rcpss %xmm0, %xmm1
; CHECK-NEXT:    mulss %xmm1, %xmm2
; CHECK-NEXT:    subss %xmm2, %xmm3
; CHECK-NEXT:    mulss %xmm1, %xmm3
; CHECK-NEXT:    addss %xmm1, %xmm3
; CHECK-NEXT:    mulss %xmm0, %xmm3
; CHECK-NEXT:    movss %xmm3, (%eax)
; CHECK-NEXT:    retl
entry:
  %div = fdiv fast float 0.000000e+00, 0.000000e+00
  store float %div, float* undef, align 4
  ret void
}

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="true" "no-jump-tables"="false" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="slm" "target-features"="+aes,+cx16,+fxsr,+mmx,+pclmul,+popcnt,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87" "unsafe-fp-math"="true" "use-soft-float"="false" }

